# Generated by Django 4.2.7 on 2025-07-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ELabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="elabels/images/"
                    ),
                ),
                (
                    "grape_variety",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vintage_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "denomination",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classification",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("alcohol", models.FloatField(blank=True, null=True)),
                ("residual_sugar", models.FloatField(blank=True, null=True)),
                ("total_acidity", models.FloatField(blank=True, null=True)),
                ("glycerin", models.FloatField(blank=True, null=True)),
                ("display_nutrition", models.JSONField(default=dict)),
                (
                    "product_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("ingredients", models.JSONField(default=list)),
                ("additional_ingredients", models.TextField(blank=True, null=True)),
                (
                    "recycling_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("recycling_materials", models.JSONField(default=list)),
                (
                    "recycling_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="elabels/recycling/"
                    ),
                ),
                ("recycling_website", models.URLField(blank=True, null=True)),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="elabels/qrcodes/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
