# Generated by Django 4.2.7 on 2025-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elabels", "0002_elabel_company_profile_elabel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elabel",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
