# Generated by Django 4.2.7 on 2025-07-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elabels", "0003_alter_elabel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elabel",
            name="qr_code",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
