# Generated by Django 4.2.7 on 2025-07-10 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("legal_name", models.CharField(blank=True, max_length=255, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("vat_id", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_number", models.CharField(blank=True, max_length=50, null=True)),
                ("eori_number", models.CharField(blank=True, max_length=50, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="companyprofiles/logos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
