# Generated by Django 4.2.7 on 2025-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companyprofiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
